# Generated by Django 3.1.12 on 2021-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handimage',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
