# Generated by Django 3.1.12 on 2021-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_handimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handimage',
            name='name',
            field=models.CharField(default='img.jpg', max_length=255),
        ),
    ]
